### ISSUE TITLE
Not working in sketch 41.2

### ISSUE THREAD

**Issue by djtillma** [youwenliang/Table-of-Contents#1]
I tried to use this plugin in the newest version of sketch with no success.  I believe it's possibly a compatibility issue.

**Comment by jonkchen** [comment]
Having the same issue on 41.2!

**Comment by youwenliang** [comment]
Thanks for the comments, there were some changes on the usage of parameters, I'll check and see if I can update the plugin!

**Comment by ayingchan** [comment]
Look forward to the update! Can't wait to use this plugin.

**Comment by youwenliang** [comment]
@ayingchan @djtillma @jonkchen 
Just Updated the plugin, let me know if you encounter any problems!
