### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [youwenliang/Table-of-Contents#2]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by acabeza1978** [comment]
I have Sketch 44.1 and I have the last version of the plugin, and it doesn't work.

I put all the title with symbols, and their name are "Header1" and "Header2"... but it doesn't works... have you any idea why?

Thanks in advance,

Alex

**Comment by youwenliang** [comment]
@acabeza1978 thanks for commenting on this, I'll take a took for the compatibility issue for version 44.1.

**Comment by acabeza1978** [comment]
Thank you @youwenliang !

Alex
