### ISSUE TITLE
TOC doesn't display after refreshing

### ISSUE THREAD

**Issue by diegorioja** [youwenliang/Table-of-Contents#3]
Using Sketch 44.1 - The example file and any other attempt at creating a TOC fails. Anyone else having this issue?

**Comment by lauggh** [comment]
Same issue. Also using Sketch 44.1

**Comment by youwenliang** [comment]
@diegorioja @lauggh 
Thanks for commenting on this, I'll take a took for the compatibility issue for version 44.1.
