### ISSUE TITLE
Did this script stop working with a recent Sketch Update?

### ISSUE THREAD

**Issue by cboese** [youwenliang/Table-of-Contents#4]
Installed the plug-in. Won't generate a TOC, even in the Example File, to refresh, where all the header structure symbols are already in place. Am I doing something wrong? Thanks.

**Comment by youwenliang** [comment]
@cboese Can you specify which version of Sketch are you using? thanks!

**Comment by cboese** [comment]
My current version is 46.2, but I'm sure I filed this a couple of versions back.

I generally update Sketch whenever the app tells me to.

Chris

**Comment by youwenliang** [comment]
@cboese Can you download again and see if it's working now? thanks!

**Comment by KlausEichinger** [comment]
Doesn't work with #47

**Comment by youwenliang** [comment]
@KlausEichinger Can you download again and see if it's working?

**Comment by KlausEichinger** [comment]
Running the update only creates a new empty layer _Table of Contents_, nothing else.  When running your example file it removes all the existing contents (on refresh).

**Comment by KlausEichinger** [comment]
Sketch 47.1 (45422)
Mac OS Sierra v10.12.6

**Comment by RadhaN108** [comment]
It's been updated!
