### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by rkonderla** [youwenliang/Table-of-Contents#5]
The plugin creates another art board, but it is blank and none of the ToC stuff is created.

**Comment by youwenliang** [comment]
@rkonderla  Can you specify which version of Sketch are you using? thanks!

**Comment by adc358** [comment]
I have the same problem and I am using version 47.1

**Comment by youwenliang** [comment]
@adc358 Can you download again and see if it's working? If not can you share a screenshot so I can know what might be the problem? thanks!

**Comment by adc358** [comment]
![screen shot 2017-10-25 at 10 13 36 am](https://user-images.githubusercontent.com/32910607/32012680-841c5f68-b96d-11e7-883c-9e23a8992d07.png)

I re-installed but getting the same result. I have left screen shot of the setup

**Comment by RadhaN108** [comment]
It's been updated!
