### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by trine-stensgaard** [youwenliang/Table-of-Contents#6]
Hi Youwenliang
I can't make your table-of-content plugin work? I am on Sketch version 49.3. When I generate a table-of-content it creates an empty blank artboard 100x100px - with no bg colour. I get the same result in your Example.sketch file.

Can you help?

Cheers
Trine

**Comment by rhathaway** [comment]
Hi @youwenliang :) I'm getting the same issue reported above in Sketch version 52. Are you still updating this plugin?

Rebecca

**Comment by RadhaN108** [comment]
It's been updated!
